site_name: MongoDB-ODM
site_description: MongoDB-ODM, NOSQL databases in Python, designed for simplicity, compatibility, and robustness.
site_url: http://localhost:8000
theme:
  name: material
  # custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: nayan32biswas/mongodb-odm
repo_url: https://github.com/nayan32biswas/mongodb-odm
edit_uri: ""
nav:
  - MongoDB-ODM: index.md
  - features.md
  - Tutorial - User Guide:
      - tutorial/index.md
      - tutorial/init_and_define_model.md
      - tutorial/connection.md
      - tutorial/create.md
      - tutorial/indexes.md
      - tutorial/find_and_filter.md
      - tutorial/find_and_sort.md
      - tutorial/find_limit_and_skip.md
      - tutorial/find_one_document.md
      - tutorial/get_document.md
      - tutorial/get_or_create.md
      - tutorial/find_raw.md
      - tutorial/aggregate.md
      - tutorial/update.md
      - tutorial/delete.md
      - Object Relationship:
        - Foreign Key Relationship: tutorial/relation/foreignkey_relationship.md
        - Many to Many Relationship: tutorial/relation/many_to_many_relationship.md
  - reference.md
  - Advanced User Guide:
      - advanced-tutorial/index.md
      - advanced-tutorial/model-inheritance.md
  - help.md
  - contributing.md
  - release-notes.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include

extra:
  analytics:
    provider: google
    property: G-Z5RC8BNFTZ
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nayan32biswas

extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js
